In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#slicing

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
# mainipulate first 5 digits
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr= arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:] = 99

In [13]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
#original array changes after slicing
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# indexing 2d array

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
#Gramming elements double brace
arr_2d[0][0] # return first row and first coulumn

5

In [6]:
arr_2d[1][1]

25

In [8]:
arr_2d [2][1] #Return third row second coloumn

40

In [9]:
arr_2d[2][2]

45

In [10]:
#Grabbing elements single brace notation

In [12]:
arr_2d[1,2] #second row Third coloumn

30